# Generated by Django 4.2.7 on 2025-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_bio_user_cases_fought_user_cases_won_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
